// ARQUIVO GERADO — tipagem, movesets e passivas shiny por espécie.
// Editável à mão: cada espécie tem entrada própria.
import type { Moveset, ShinyPassive } from "./moves";

export const MOVESETS: Record<string, Moveset> = {
  "flarepup": { types: ["fire"], moves: ["fire_fang", "flame_charge", "ember", "quick_attack"], status: "will_o_wisp" },
  "aquakitty": { types: ["water"], moves: ["water_gun", "bubble_beam", "surf", "quick_attack"], status: "rest" },
  "leafox": { types: ["grass"], moves: ["vine_whip", "razor_leaf", "petal_blizzard", "quick_attack"], status: "sleep_powder" },
  "voltbun": { types: ["electric"], moves: ["thunder_fang", "thunder_shock", "thunderbolt", "quick_attack"], status: "thunder_wave" },
  "shadepup": { types: ["dark"], moves: ["dark_pulse", "bite", "night_slash", "quick_attack"], status: "nasty_plot" },
  "rato_bomba": { types: ["fire", "normal"], moves: ["fire_fang", "flame_charge", "ember", "tackle"], status: "will_o_wisp" },
  "steamcub": { types: ["fire", "water"], moves: ["fire_fang", "flame_charge", "ember", "waterfall"], status: "will_o_wisp" },
  "emberleaf": { types: ["fire", "grass"], moves: ["fire_fang", "flame_charge", "ember", "vine_whip"], status: "will_o_wisp" },
  "sparkpup": { types: ["fire", "electric"], moves: ["fire_fang", "flame_charge", "ember", "thunder_fang"], status: "will_o_wisp" },
  "cinderwisp": { types: ["fire", "ghost"], moves: ["ember", "flamethrower", "fire_blast", "shadow_ball"], status: "will_o_wisp" },
  "mossfin": { types: ["water", "grass"], moves: ["water_gun", "bubble_beam", "surf", "giga_drain"], status: "rest" },
  "stormtad": { types: ["water", "electric"], moves: ["water_gun", "bubble_beam", "surf", "thunder_shock"], status: "rest" },
  "tidewraith": { types: ["water", "ghost"], moves: ["waterfall", "aqua_tail", "water_gun", "lick"], status: "rest" },
  "voltsprout": { types: ["grass", "electric"], moves: ["giga_drain", "solar_beam", "vine_whip", "thunder_shock"], status: "recover" },
  "nightbloom": { types: ["grass", "ghost"], moves: ["giga_drain", "solar_beam", "vine_whip", "shadow_ball"], status: "sleep_powder" },
  "voidspark": { types: ["electric", "dark"], moves: ["thunder_fang", "thunder_shock", "thunderbolt", "bite"], status: "thunder_wave" },
  "rockpup": { types: ["rock"], moves: ["rock_throw", "rock_slide", "stone_edge", "quick_attack"], status: "rock_polish" },
  "magmaboulder": { types: ["ground", "fire"], moves: ["bulldoze", "dig", "earthquake", "fire_fang"], status: "harden" },
  "mudpaw": { types: ["ground", "water"], moves: ["bulldoze", "dig", "earthquake", "waterfall"], status: "harden" },
  "crystalsprite": { types: ["ground", "electric"], moves: ["mud_slap", "bulldoze", "dig", "thunder_shock"], status: "harden" },
  "onca_sombria": { types: ["dark"], moves: ["bite", "night_slash", "crunch", "quick_attack"], status: "nasty_plot" },
  "leao_dourado": { types: ["normal"], moves: ["tackle", "quick_attack", "body_slam", "slash"], status: "swords_dance" },
  "tigre_infernal": { types: ["fire"], moves: ["fire_fang", "flame_charge", "ember", "quick_attack"], status: "will_o_wisp" },
  "pantera_negra": { types: ["dark"], moves: ["bite", "night_slash", "crunch", "quick_attack"], status: "nasty_plot" },
  "pantera_aurea": { types: ["dark", "fairy"], moves: ["dark_pulse", "bite", "night_slash", "fairy_wind"], status: "nasty_plot" },
  "macaco_prego": { types: ["grass", "fighting"], moves: ["vine_whip", "razor_leaf", "petal_blizzard", "karate_chop"], status: "sleep_powder" },
  "tubarao_abissal": { types: ["water"], moves: ["waterfall", "aqua_tail", "water_gun", "quick_attack"], status: "rest" },
  "polvo_venenoso": { types: ["water", "poison"], moves: ["water_gun", "bubble_beam", "surf", "acid"], status: "rest" },
  "cobra_sangrenta": { types: ["poison", "dark"], moves: ["poison_fang", "acid", "sludge_bomb", "bite"], status: "toxic" },
  "borboleta_sonifera": { types: ["bug", "psychic"], moves: ["bug_buzz", "bug_bite", "fury_cutter", "confusion"], status: "string_shot" },
  "urso_polar": { types: ["ice"], moves: ["ice_shard", "ice_fang", "ice_beam", "quick_attack"], status: "aurora_veil" },
  "jacare_ancestral": { types: ["water", "ground"], moves: ["waterfall", "aqua_tail", "water_gun", "bulldoze"], status: "rest" },
  "gorila_titan": { types: ["fighting"], moves: ["karate_chop", "brick_break", "close_combat", "quick_attack"], status: "bulk_up" },
  "aguia_cega": { types: ["flying"], moves: ["wing_attack", "brave_bird", "gust", "quick_attack"], status: "roost" },
  "lobo_lua_sangrenta": { types: ["dark"], moves: ["bite", "night_slash", "crunch", "quick_attack"], status: "nasty_plot" },
  "dragao_branco": { types: ["dragon", "ice"], moves: ["dragon_breath", "dragon_pulse", "dragon_claw", "ice_beam"], status: "recover" },
  "dragao_negro": { types: ["dragon", "dark"], moves: ["dragon_claw", "outrage", "dragon_breath", "bite"], status: "dragon_dance" },
  "fenix_vermelha": { types: ["fire", "flying"], moves: ["fire_fang", "flame_charge", "ember", "wing_attack"], status: "will_o_wisp" },
  "fenix_negra": { types: ["fire", "dark"], moves: ["fire_fang", "flame_charge", "ember", "bite"], status: "will_o_wisp" },
  "gengar": { types: ["ghost", "poison"], moves: ["shadow_ball", "sludge_bomb", "dark_pulse", "dream_eater"], status: "hypnosis" },
  "fenix_azul": { types: ["ice", "flying"], moves: ["ice_beam", "blizzard", "ice_shard", "gust"], status: "recover" },
  "dragao_fogo": { types: ["dragon", "fire"], moves: ["dragon_breath", "dragon_pulse", "dragon_claw", "ember"], status: "dragon_dance" },
  "foca_glacial": { types: ["ice", "water"], moves: ["ice_beam", "blizzard", "ice_shard", "water_gun"], status: "recover" },
  "lobo_artico": { types: ["ice"], moves: ["ice_shard", "ice_fang", "ice_beam", "quick_attack"], status: "aurora_veil" },
  "tartaruga_ancestral": { types: ["water", "rock"], moves: ["waterfall", "aqua_tail", "water_gun", "rock_throw"], status: "rest" },
  "corvo_sombras": { types: ["dark", "flying"], moves: ["dark_pulse", "bite", "night_slash", "gust"], status: "nasty_plot" },
  "lince_dourado": { types: ["normal"], moves: ["tackle", "quick_attack", "body_slam", "slash"], status: "swords_dance" },
  "leoa_trovao": { types: ["electric"], moves: ["thunder_fang", "thunder_shock", "thunderbolt", "quick_attack"], status: "thunder_wave" },
  "panda": { types: ["normal", "fighting"], moves: ["hyper_beam", "tackle", "quick_attack", "aura_sphere"], status: "recover" },
  "golem_pedra": { types: ["rock"], moves: ["rock_throw", "rock_slide", "stone_edge", "quick_attack"], status: "recover" },
  "trex": { types: ["dragon", "ground"], moves: ["dragon_claw", "outrage", "dragon_breath", "bulldoze"], status: "dragon_dance" },
  "pterossauro": { types: ["rock", "flying"], moves: ["rock_throw", "rock_slide", "stone_edge", "wing_attack"], status: "rock_polish" },
  "triceratops_colossal": { types: ["rock", "ground"], moves: ["rock_throw", "rock_slide", "stone_edge", "bulldoze"], status: "rock_polish" },
  "fantasminha": { types: ["ghost"], moves: ["shadow_ball", "night_shade", "lick", "quick_attack"], status: "curse" },
  "raposa_espectral": { types: ["ghost", "dark"], moves: ["lick", "shadow_punch", "shadow_claw", "bite"], status: "curse" },
  "orangotango": { types: ["fighting"], moves: ["aura_sphere", "karate_chop", "brick_break", "quick_attack"], status: "recover" },
  "porco_espinho": { types: ["normal", "ground"], moves: ["tackle", "quick_attack", "body_slam", "bulldoze"], status: "swords_dance" },
  "urubu_carniceiro": { types: ["flying", "dark"], moves: ["wing_attack", "brave_bird", "gust", "bite"], status: "roost" },
  "pikachu": { types: ["electric"], moves: ["thunderbolt", "quick_attack", "thunder", "electro_ball"], status: "nuzzle" },
  "brasagarto": { types: ["fire"], moves: ["fire_fang", "flame_charge", "ember", "quick_attack"], status: "will_o_wisp" },
  "cascatoruga": { types: ["water"], moves: ["waterfall", "aqua_tail", "water_gun", "quick_attack"], status: "rest" },
  "folhassauro": { types: ["grass"], moves: ["giga_drain", "solar_beam", "vine_whip", "quick_attack"], status: "recover" },
  "faiscorato": { types: ["electric"], moves: ["thunder_fang", "thunder_shock", "thunderbolt", "quick_attack"], status: "thunder_wave" },
  "rochapunho": { types: ["rock", "fighting"], moves: ["rock_throw", "rock_slide", "stone_edge", "karate_chop"], status: "rock_polish" },
  "chamalobo": { types: ["fire", "dark"], moves: ["fire_fang", "flame_charge", "ember", "bite"], status: "will_o_wisp" },
  "psicoluna": { types: ["psychic", "fairy"], moves: ["confusion", "psybeam", "psychic", "fairy_wind"], status: "hypnosis" },
  "vespanoxa": { types: ["bug", "poison"], moves: ["bug_bite", "fury_cutter", "x_scissor", "poison_fang"], status: "string_shot" },
  "ventasa": { types: ["flying"], moves: ["wing_attack", "brave_bird", "gust", "quick_attack"], status: "roost" },
  "dracomarino": { types: ["water", "dragon"], moves: ["water_gun", "bubble_beam", "surf", "dragon_breath"], status: "rest" },
  "rinoceronte_guardiao": { types: ["ground", "steel"], moves: ["bulldoze", "dig", "earthquake", "metal_claw"], status: "harden" },
  "elefante_ancestral": { types: ["ground"], moves: ["bulldoze", "dig", "earthquake", "quick_attack"], status: "harden" },
  "arara_corsaria": { types: ["flying", "normal"], moves: ["wing_attack", "brave_bird", "gust", "tackle"], status: "roost" },
  "tigre_relampago": { types: ["electric"], moves: ["thunder_fang", "thunder_shock", "thunderbolt", "quick_attack"], status: "thunder_wave" },
  "leopardo_fantasma": { types: ["ghost", "dark"], moves: ["lick", "shadow_punch", "shadow_claw", "bite"], status: "curse" },
  "hiena_carniceira": { types: ["dark"], moves: ["bite", "night_slash", "crunch", "quick_attack"], status: "nasty_plot" },
  "coruja_branca": { types: ["flying", "fairy"], moves: ["gust", "air_slash", "wing_attack", "fairy_wind"], status: "roost" },
  "escorpiao_deserto": { types: ["poison", "ground"], moves: ["poison_fang", "acid", "sludge_bomb", "bulldoze"], status: "toxic" },
  "coruja_negra": { types: ["ghost", "flying"], moves: ["shadow_ball", "night_shade", "lick", "gust"], status: "curse" },
  "coruja_psiquica": { types: ["psychic", "flying"], moves: ["confusion", "psybeam", "psychic", "gust"], status: "hypnosis" },
  "alakazam": { types: ["psychic"], moves: ["psychic", "psyshock", "confusion", "psybeam"], status: "recover" },
  "gastly": { types: ["ghost", "poison"], moves: ["lick", "shadow_ball", "night_shade", "sludge_bomb"], status: "hypnosis" },
  "haunter": { types: ["ghost", "poison"], moves: ["shadow_ball", "sludge_bomb", "night_shade", "confusion"], status: "hypnosis" },
  "abra": { types: ["psychic"], moves: ["confusion", "psybeam", "psychic", "quick_attack"], status: "hypnosis" },
  "kadabra": { types: ["psychic"], moves: ["psybeam", "psychic", "confusion", "psyshock"], status: "recover" },
  "charmander": { types: ["fire"], moves: ["ember", "dragon_claw", "fire_fang", "flame_charge"], status: "will_o_wisp" },
  "charmeleon": { types: ["fire"], moves: ["flamethrower", "dragon_claw", "fire_fang", "flame_charge"], status: "will_o_wisp" },
  "charizard": { types: ["fire", "flying"], moves: ["flamethrower", "air_slash", "fire_blast", "dragon_claw"], status: "roost" },
  "squirtle": { types: ["water"], moves: ["water_gun", "aqua_tail", "waterfall", "quick_attack"], status: "rest" },
  "wartortle": { types: ["water"], moves: ["water_pulse", "aqua_tail", "waterfall", "water_gun"], status: "rest" },
  "blastoise": { types: ["water"], moves: ["hydro_pump", "aqua_tail", "surf", "ice_beam"], status: "rest" },
  "bulbasaur": { types: ["grass", "poison"], moves: ["vine_whip", "razor_leaf", "giga_drain", "solar_beam"], status: "recover" },
  "ivysaur": { types: ["grass", "poison"], moves: ["razor_leaf", "petal_dance", "giga_drain", "solar_beam"], status: "recover" },
  "venusaur": { types: ["grass", "poison"], moves: ["solar_beam", "sludge_bomb", "giga_drain", "razor_leaf"], status: "sleep_powder" },
  "caterpie": { types: ["bug"], moves: ["bug_bite", "tackle", "fury_cutter", "x_scissor"], status: "string_shot" },
  "metapod": { types: ["bug"], moves: ["harden", "struggle_bug", "bug_bite", "fury_cutter"], status: "string_shot" },
  "butterfree": { types: ["bug", "flying"], moves: ["air_slash", "bug_buzz", "psybeam", "gust"], status: "sleep_powder" },
  "weedle": { types: ["bug", "poison"], moves: ["poison_sting", "bug_bite", "fury_cutter", "x_scissor"], status: "string_shot" },
  "kakuna": { types: ["bug", "poison"], moves: ["poison_sting", "harden", "bug_bite", "fury_cutter"], status: "string_shot" },
  "beedrill": { types: ["bug", "poison"], moves: ["twineedle", "poison_jab", "x_scissor", "poison_fang"], status: "toxic" },
  "pidgey": { types: ["normal", "flying"], moves: ["gust", "quick_attack", "tackle", "body_slam"], status: "swords_dance" },
  "pidgeotto": { types: ["normal", "flying"], moves: ["wing_attack", "aerial_ace", "tackle", "quick_attack"], status: "swords_dance" },
  "pidgeot": { types: ["normal", "flying"], moves: ["hurricane", "brave_bird", "tackle", "quick_attack"], status: "swords_dance" },
  "rattata": { types: ["normal"], moves: ["quick_attack", "hyper_fang", "tackle", "body_slam"], status: "swords_dance" },
  "raticate": { types: ["normal"], moves: ["hyper_fang", "crunch", "tackle", "quick_attack"], status: "swords_dance" },
  "fearow": { types: ["normal", "flying"], moves: ["drill_peck", "aerial_ace", "tackle", "quick_attack"], status: "swords_dance" },
  "ekans": { types: ["poison"], moves: ["poison_sting", "bite", "poison_fang", "acid"], status: "toxic" },
  "arbok": { types: ["poison"], moves: ["poison_jab", "crunch", "poison_fang", "acid"], status: "toxic" },
  "raichu": { types: ["electric"], moves: ["thunderbolt", "thunder_punch", "thunder", "electro_ball"], status: "nuzzle" },
  "sandshrew": { types: ["ground"], moves: ["dig", "slash", "bulldoze", "earthquake"], status: "harden" },
  "sandslash": { types: ["ground"], moves: ["earthquake", "night_slash", "bulldoze", "dig"], status: "harden" },
  "nidoran_f": { types: ["poison"], moves: ["poison_sting", "double_kick", "poison_fang", "acid"], status: "toxic" },
  "nidorina": { types: ["poison"], moves: ["poison_fang", "double_kick", "acid", "sludge_bomb"], status: "toxic" },
  "nidoqueen": { types: ["poison", "ground"], moves: ["earth_power", "poison_jab", "earthquake", "sludge_bomb"], status: "toxic" },
  "nidoran_m": { types: ["poison"], moves: ["poison_sting", "peck", "poison_fang", "acid"], status: "toxic" },
  "nidorino": { types: ["poison"], moves: ["poison_jab", "double_kick", "poison_fang", "acid"], status: "toxic" },
  "nidoking": { types: ["poison", "ground"], moves: ["earthquake", "poison_jab", "sludge_bomb", "poison_fang"], status: "toxic" },
  "clefairy": { types: ["fairy"], moves: ["disarming_voice", "moonblast", "fairy_wind", "draining_kiss"], status: "moonlight" },
  "clefable": { types: ["fairy"], moves: ["moonblast", "psychic", "dazzling_gleam", "psyshock"], status: "moonlight" },
  "vulpix": { types: ["fire"], moves: ["ember", "quick_attack", "fire_fang", "flame_charge"], status: "will_o_wisp" },
  "ninetales": { types: ["fire"], moves: ["flamethrower", "dazzling_gleam", "fire_blast", "dark_pulse"], status: "will_o_wisp" },
  "jigglypuff": { types: ["normal", "fairy"], moves: ["pound", "disarming_voice", "hyper_beam", "tackle"], status: "recover" },
  "wigglytuff": { types: ["normal", "fairy"], moves: ["hyper_voice", "play_rough", "dazzling_gleam", "body_slam"], status: "moonlight" },
  "zubat": { types: ["poison", "flying"], moves: ["wing_attack", "poison_fang", "acid", "sludge_bomb"], status: "toxic" },
  "golbat": { types: ["poison", "flying"], moves: ["air_slash", "poison_fang", "acid", "sludge_bomb"], status: "toxic" },
  "oddish": { types: ["grass", "poison"], moves: ["absorb", "acid", "giga_drain", "solar_beam"], status: "sleep_powder" },
  "gloom": { types: ["grass", "poison"], moves: ["mega_drain", "acid", "giga_drain", "solar_beam"], status: "sleep_powder" },
  "vileplume": { types: ["grass", "poison"], moves: ["petal_dance", "sludge_bomb", "giga_drain", "solar_beam"], status: "sleep_powder" },
  "paras": { types: ["bug", "grass"], moves: ["leech_life", "seed_bomb", "bug_bite", "fury_cutter"], status: "string_shot" },
  "parasect": { types: ["bug", "grass"], moves: ["x_scissor", "giga_drain", "bug_bite", "fury_cutter"], status: "string_shot" },
  "venonat": { types: ["bug", "poison"], moves: ["confusion", "bug_buzz", "bug_bite", "fury_cutter"], status: "string_shot" },
  "venomoth": { types: ["bug", "poison"], moves: ["psychic", "bug_buzz", "bug_bite", "fury_cutter"], status: "string_shot" },
  "diglett": { types: ["ground"], moves: ["dig", "mud_slap", "bulldoze", "earthquake"], status: "harden" },
  "dugtrio": { types: ["ground"], moves: ["earthquake", "slash", "dig", "bulldoze"], status: "rock_polish" },
  "meowth": { types: ["normal"], moves: ["scratch", "bite", "tackle", "quick_attack"], status: "swords_dance" },
  "persian": { types: ["normal"], moves: ["slash", "night_slash", "crunch", "body_slam"], status: "agility" },
  "psyduck": { types: ["water"], moves: ["water_pulse", "confusion", "water_gun", "bubble_beam"], status: "rest" },
  "golduck": { types: ["water"], moves: ["surf", "psychic", "hydro_pump", "ice_beam"], status: "calm_mind" },
  "mankey": { types: ["fighting"], moves: ["low_kick", "cross_chop", "karate_chop", "brick_break"], status: "bulk_up" },
  "primeape": { types: ["fighting"], moves: ["close_combat", "rage_fist", "brick_break", "crunch"], status: "bulk_up" },
  "growlithe": { types: ["fire"], moves: ["flame_wheel", "crunch", "fire_fang", "flame_charge"], status: "will_o_wisp" },
  "arcanine": { types: ["fire"], moves: ["flamethrower", "extreme_speed", "fire_fang", "close_combat"], status: "will_o_wisp" },
  "poliwag": { types: ["water"], moves: ["water_gun", "bubble_beam", "surf", "quick_attack"], status: "rest" },
  "poliwhirl": { types: ["water"], moves: ["water_pulse", "body_slam", "waterfall", "aqua_tail"], status: "rest" },
  "poliwrath": { types: ["water", "fighting"], moves: ["dynamic_punch", "hydro_pump", "close_combat", "brick_break"], status: "bulk_up" },
  "machop": { types: ["fighting"], moves: ["low_kick", "karate_chop", "brick_break", "close_combat"], status: "bulk_up" },
  "machoke": { types: ["fighting"], moves: ["brick_break", "submission", "karate_chop", "close_combat"], status: "bulk_up" },
  "machamp": { types: ["fighting"], moves: ["dynamic_punch", "close_combat", "brick_break", "karate_chop"], status: "bulk_up" },
  "bellsprout": { types: ["grass", "poison"], moves: ["vine_whip", "acid", "giga_drain", "solar_beam"], status: "sleep_powder" },
  "weepinbell": { types: ["grass", "poison"], moves: ["razor_leaf", "acid", "giga_drain", "solar_beam"], status: "sleep_powder" },
  "victreebel": { types: ["grass", "poison"], moves: ["leaf_blade", "sludge_bomb", "giga_drain", "solar_beam"], status: "sleep_powder" },
  "tentacool": { types: ["water", "poison"], moves: ["water_pulse", "acid", "water_gun", "bubble_beam"], status: "rest" },
  "tentacruel": { types: ["water", "poison"], moves: ["surf", "sludge_wave", "sludge_bomb", "hydro_pump"], status: "toxic" },
  "geodude": { types: ["rock", "ground"], moves: ["rock_throw", "rock_tomb", "rock_slide", "stone_edge"], status: "rock_polish" },
  "graveler": { types: ["rock", "ground"], moves: ["rock_slide", "earthquake", "rock_throw", "stone_edge"], status: "rock_polish" },
  "golem": { types: ["rock", "ground"], moves: ["rock_slide", "earthquake", "stone_edge", "body_slam"], status: "iron_defense" },
  "ponyta": { types: ["fire"], moves: ["flame_charge", "stomp", "fire_fang", "ember"], status: "will_o_wisp" },
  "rapidash": { types: ["fire"], moves: ["flare_blitz", "megahorn", "flame_charge", "fire_fang"], status: "agility" },
  "slowpoke": { types: ["water", "psychic"], moves: ["water_pulse", "confusion", "waterfall", "aqua_tail"], status: "rest" },
  "slowbro": { types: ["water", "psychic"], moves: ["psychic", "surf", "psyshock", "ice_beam"], status: "barrier" },
  "magnemite": { types: ["electric", "steel"], moves: ["thunder_shock", "flash_cannon", "thunderbolt", "electro_ball"], status: "thunder_wave" },
  "magneton": { types: ["electric", "steel"], moves: ["thunderbolt", "flash_cannon", "thunder", "thunder_shock"], status: "thunder_wave" },
  "farfetchd": { types: ["normal", "flying"], moves: ["aerial_ace", "slash", "tackle", "quick_attack"], status: "swords_dance" },
  "doduo": { types: ["normal", "flying"], moves: ["peck", "drill_peck", "tackle", "quick_attack"], status: "swords_dance" },
  "dodrio": { types: ["normal", "flying"], moves: ["drill_peck", "tri_attack", "brave_bird", "wing_attack"], status: "agility" },
  "seel": { types: ["water"], moves: ["ice_shard", "aqua_jet", "waterfall", "aqua_tail"], status: "rest" },
  "dewgong": { types: ["water", "ice"], moves: ["ice_beam", "surf", "waterfall", "aqua_tail"], status: "rest" },
  "grimer": { types: ["poison"], moves: ["sludge", "mud_bomb", "poison_fang", "acid"], status: "toxic" },
  "muk": { types: ["poison"], moves: ["sludge_wave", "gunk_shot", "sludge_bomb", "venoshock"], status: "toxic" },
  "shellder": { types: ["water"], moves: ["icicle_spear", "razor_shell", "waterfall", "aqua_tail"], status: "rest" },
  "cloyster": { types: ["water", "ice"], moves: ["ice_beam", "hydro_pump", "ice_shard", "surf"], status: "iron_defense" },
  "onix": { types: ["rock", "ground"], moves: ["rock_slide", "earthquake", "stone_edge", "iron_head"], status: "iron_defense" },
  "drowzee": { types: ["psychic"], moves: ["confusion", "psybeam", "psychic", "quick_attack"], status: "hypnosis" },
  "hypno": { types: ["psychic"], moves: ["psychic", "zen_headbutt", "psyshock", "shadow_ball"], status: "hypnosis" },
  "krabby": { types: ["water"], moves: ["crabhammer", "x_scissor", "waterfall", "aqua_tail"], status: "rest" },
  "kingler": { types: ["water"], moves: ["crabhammer", "guillotine", "waterfall", "aqua_tail"], status: "rest" },
  "voltorb": { types: ["electric"], moves: ["spark", "electro_ball", "thunder_shock", "thunderbolt"], status: "thunder_wave" },
  "electrode": { types: ["electric"], moves: ["thunderbolt", "explosion", "thunder", "electro_ball"], status: "thunder_wave" },
  "exeggcute": { types: ["grass", "psychic"], moves: ["confusion", "bullet_seed", "giga_drain", "solar_beam"], status: "sleep_powder" },
  "exeggutor": { types: ["grass", "psychic"], moves: ["psychic", "giga_drain", "solar_beam", "psybeam"], status: "sleep_powder" },
  "cubone": { types: ["ground"], moves: ["bone_club", "bonemerang", "bulldoze", "dig"], status: "harden" },
  "marowak": { types: ["ground"], moves: ["bonemerang", "earthquake", "bulldoze", "stone_edge"], status: "harden" },
  "hitmonlee": { types: ["fighting"], moves: ["high_jump_kick", "blaze_kick", "close_combat", "brick_break"], status: "bulk_up" },
  "hitmonchan": { types: ["fighting"], moves: ["drain_punch", "ice_punch", "close_combat", "brick_break"], status: "bulk_up" },
  "lickitung": { types: ["normal"], moves: ["body_slam", "power_whip", "lick", "slash"], status: "swords_dance" },
  "koffing": { types: ["poison"], moves: ["smog", "sludge_bomb", "acid", "venoshock"], status: "toxic" },
  "weezing": { types: ["poison"], moves: ["sludge_bomb", "dark_pulse", "venoshock", "acid"], status: "toxic" },
  "rhyhorn": { types: ["ground", "rock"], moves: ["rock_blast", "drill_run", "bulldoze", "dig"], status: "harden" },
  "rhydon": { types: ["ground", "rock"], moves: ["earthquake", "rock_slide", "stone_edge", "iron_head"], status: "iron_defense" },
  "chansey": { types: ["normal"], moves: ["egg_bomb", "dazzling_gleam", "body_slam", "psyshock"], status: "rest" },
  "tangela": { types: ["grass"], moves: ["vine_whip", "power_whip", "razor_leaf", "petal_blizzard"], status: "sleep_powder" },
  "kangaskhan": { types: ["normal"], moves: ["dizzy_punch", "crunch", "body_slam", "earthquake"], status: "swords_dance" },
  "horsea": { types: ["water"], moves: ["water_gun", "bubble_beam", "surf", "quick_attack"], status: "rest" },
  "seadra": { types: ["water"], moves: ["water_pulse", "hydro_pump", "water_gun", "bubble_beam"], status: "rest" },
  "goldeen": { types: ["water"], moves: ["water_pulse", "aqua_tail", "waterfall", "water_gun"], status: "rest" },
  "seaking": { types: ["water"], moves: ["waterfall", "megahorn", "aqua_tail", "ice_beam"], status: "swords_dance" },
  "staryu": { types: ["water"], moves: ["water_pulse", "psybeam", "water_gun", "bubble_beam"], status: "rest" },
  "starmie": { types: ["water", "psychic"], moves: ["psychic", "surf", "hydro_pump", "ice_beam"], status: "recover" },
  "mrmime": { types: ["psychic", "fairy"], moves: ["psychic", "dazzling_gleam", "psybeam", "psyshock"], status: "barrier" },
  "scyther": { types: ["bug", "flying"], moves: ["x_scissor", "aerial_ace", "wing_attack", "fury_cutter"], status: "swords_dance" },
  "jynx": { types: ["ice", "psychic"], moves: ["ice_beam", "psychic", "blizzard", "draining_kiss"], status: "hypnosis" },
  "electabuzz": { types: ["electric"], moves: ["thunder_punch", "thunderbolt", "thunder", "brick_break"], status: "thunder_wave" },
  "magmar": { types: ["fire"], moves: ["flamethrower", "fire_punch", "fire_blast", "brick_break"], status: "will_o_wisp" },
  "pinsir": { types: ["bug"], moves: ["x_scissor", "brick_break", "close_combat", "fury_cutter"], status: "swords_dance" },
  "tauros": { types: ["normal"], moves: ["take_down", "zen_headbutt", "body_slam", "crunch"], status: "swords_dance" },
  "magikarp": { types: ["water"], moves: ["splash", "tackle", "quick_attack", "waterfall"], status: "harden" },
  "gyarados": { types: ["water", "flying"], moves: ["waterfall", "crunch", "aqua_tail", "ice_fang"], status: "dragon_dance" },
  "lapras": { types: ["water", "ice"], moves: ["ice_beam", "surf", "hydro_pump", "body_slam"], status: "rest" },
  "ditto": { types: ["normal"], moves: [""tackle", "quick_attack", "body_slam"], status: "transform" },
  "eevee": { types: ["normal"], moves: ["quick_attack", "bite", "body_slam", "slash"], status: "swords_dance" },
  "vaporeon": { types: ["water"], moves: ["surf", "ice_beam", "hydro_pump", "water_gun"], status: "rest" },
  "jolteon": { types: ["electric"], moves: ["thunderbolt", "pin_missile", "thunder", "electro_ball"], status: "agility" },
  "flareon": { types: ["fire"], moves: ["flamethrower", "fire_fang", "fire_blast", "ember"], status: "swords_dance" },
  "porygon": { types: ["normal"], moves: ["tri_attack", "psybeam", "flash_cannon", "psyshock"], status: "recover" },
  "omanyte": { types: ["rock", "water"], moves: ["water_pulse", "ancient_power", "rock_throw", "rock_slide"], status: "rock_polish" },
  "kabuto": { types: ["rock", "water"], moves: ["aqua_jet", "rock_slide", "rock_throw", "stone_edge"], status: "rock_polish" },
  "kabutops": { types: ["rock", "water"], moves: ["razor_shell", "x_scissor", "stone_edge", "aqua_tail"], status: "swords_dance" },
  "aerodactyl": { types: ["rock", "flying"], moves: ["rock_slide", "aerial_ace", "stone_edge", "brave_bird"], status: "rock_polish" },
  "snorlax": { types: ["normal"], moves: ["body_slam", "crunch", "earthquake", "hyper_beam"], status: "rest" },
  "articuno": { types: ["ice", "flying"], moves: ["ice_beam", "hurricane", "blizzard", "air_slash"], status: "roost" },
  "zapdos": { types: ["electric", "flying"], moves: ["thunderbolt", "drill_peck", "thunder", "air_slash"], status: "roost" },
  "moltres": { types: ["fire", "flying"], moves: ["flamethrower", "air_slash", "fire_blast", "ember"], status: "roost" },
  "dratini": { types: ["dragon"], moves: ["dragon_breath", "aqua_tail", "dragon_claw", "outrage"], status: "dragon_dance" },
  "dragonair": { types: ["dragon"], moves: ["dragon_pulse", "aqua_tail", "dragon_breath", "dragon_claw"], status: "dragon_dance" },
  "dragonite": { types: ["dragon", "flying"], moves: ["dragon_claw", "hurricane", "outrage", "brave_bird"], status: "dragon_dance" },
  "omastar": { types: ["rock", "water"], moves: ["hydro_pump", "rock_slide", "stone_edge", "surf"], status: "iron_defense" },
  "mewtwo": { types: ["psychic"], moves: ["psychic", "psystrike", "shadow_ball", "aura_sphere"], status: "recover" },
  "mew": { types: ["psychic"], moves: ["psychic", "aura_sphere", "ice_beam", "dazzling_gleam"], status: "recover" },
};

export const SHINY_PASSIVES: Record<string, ShinyPassive> = {
  "flarepup": { name: "Chama Interior de Flarepup", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "aquakitty": { name: "Mar\u00e9 Prism\u00e1tica de Aquakitty", emoji: "\ud83d\udc9a", kind: "regen", value: 0.04, description: "\u2728 regenera 4% do HP m\u00e1ximo por turno." },
  "leafox": { name: "Seiva Ancestral de Leafox", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "voltbun": { name: "Carga Prism\u00e1tica de Voltbun", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "shadepup": { name: "Sombra Perfeita de Shadepup", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "rato_bomba": { name: "Chama Interior de Rato Bomba", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "steamcub": { name: "Chama Interior de Steamcub", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "emberleaf": { name: "Chama Interior de Emberleaf", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "sparkpup": { name: "Chama Interior de Sparkpup", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "cinderwisp": { name: "Chama Interior de Cinderwisp", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "mossfin": { name: "Mar\u00e9 Prism\u00e1tica de Mossfin", emoji: "\ud83d\udc9a", kind: "regen", value: 0.04, description: "\u2728 regenera 4% do HP m\u00e1ximo por turno." },
  "stormtad": { name: "Mar\u00e9 Prism\u00e1tica de Stormtad", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "tidewraith": { name: "Mar\u00e9 Prism\u00e1tica de Tidewraith", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "voltsprout": { name: "Seiva Ancestral de Voltsprout", emoji: "\ud83d\udc9a", kind: "regen", value: 0.04, description: "\u2728 regenera 4% do HP m\u00e1ximo por turno." },
  "nightbloom": { name: "Seiva Ancestral de Nightbloom", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "voidspark": { name: "Carga Prism\u00e1tica de Voidspark", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "rockpup": { name: "N\u00facleo de Pedra de Rockpup", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "magmaboulder": { name: "Pele de Rocha de Magmaboulder", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "mudpaw": { name: "Pele de Rocha de Mudpaw", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "crystalsprite": { name: "Pele de Rocha de Crystalsprite", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "onca_sombria": { name: "Sombra Perfeita de On\u00e7a Sombria", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "leao_dourado": { name: "Instinto de Le\u00e3o Dourado", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "tigre_infernal": { name: "Chama Interior de Tigre Infernal", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "pantera_negra": { name: "Sombra Perfeita de Pantera Negra", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "pantera_aurea": { name: "Sombra Perfeita de Pantera \u00c1urea", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "macaco_prego": { name: "Seiva Ancestral de Macaco-Prego", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "tubarao_abissal": { name: "Mar\u00e9 Prism\u00e1tica de Tubar\u00e3o Abissal", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "polvo_venenoso": { name: "Mar\u00e9 Prism\u00e1tica de Polvo Venenoso", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "cobra_sangrenta": { name: "Sangue T\u00f3xico de Cobra Sangrenta", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "borboleta_sonifera": { name: "Exoesqueleto Cromado de Borboleta Son\u00edfera", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "urso_polar": { name: "Cora\u00e7\u00e3o de Gelo de Urso Polar", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "jacare_ancestral": { name: "Mar\u00e9 Prism\u00e1tica de Jacar\u00e9 Ancestral", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "gorila_titan": { name: "Esp\u00edrito de Luta de Gorila Tit\u00e3", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "aguia_cega": { name: "Ventos Livres de \u00c1guia Ofuscante", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "lobo_lua_sangrenta": { name: "Sombra Perfeita de Lobo da Lua Sangrenta", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "dragao_branco": { name: "Heran\u00e7a Drac\u00f4nica de Drag\u00e3o Branco", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "dragao_negro": { name: "Heran\u00e7a Drac\u00f4nica de Drag\u00e3o Negro", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "fenix_vermelha": { name: "Chama Interior de F\u00eanix Vermelha", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "fenix_negra": { name: "Chama Interior de F\u00eanix Negra", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "gengar": { name: "V\u00e9u Espectral de Gengar", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "fenix_azul": { name: "Cora\u00e7\u00e3o de Gelo de F\u00eanix Azul", emoji: "\ud83d\udc9a", kind: "regen", value: 0.04, description: "\u2728 regenera 4% do HP m\u00e1ximo por turno." },
  "dragao_fogo": { name: "Heran\u00e7a Drac\u00f4nica de Drag\u00e3o de Fogo", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "foca_glacial": { name: "Cora\u00e7\u00e3o de Gelo de Foca Glacial", emoji: "\ud83d\udc9a", kind: "regen", value: 0.04, description: "\u2728 regenera 4% do HP m\u00e1ximo por turno." },
  "lobo_artico": { name: "Cora\u00e7\u00e3o de Gelo de Lobo \u00c1rtico", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "tartaruga_ancestral": { name: "Mar\u00e9 Prism\u00e1tica de Tartaruga Ancestral", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "corvo_sombras": { name: "Sombra Perfeita de Corvo das Sombras", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "lince_dourado": { name: "Instinto de Lince Dourado", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "leoa_trovao": { name: "Carga Prism\u00e1tica de Leoa Trov\u00e3o", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "panda": { name: "Instinto de Panda", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "golem_pedra": { name: "N\u00facleo de Pedra de Golem de Pedra", emoji: "\ud83d\udc9a", kind: "regen", value: 0.04, description: "\u2728 regenera 4% do HP m\u00e1ximo por turno." },
  "trex": { name: "Heran\u00e7a Drac\u00f4nica de T-Rex", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "pterossauro": { name: "N\u00facleo de Pedra de Pterossauro", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "triceratops_colossal": { name: "N\u00facleo de Pedra de Triceratops Colossal", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "fantasminha": { name: "V\u00e9u Espectral de ???", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "raposa_espectral": { name: "V\u00e9u Espectral de Raposa Espectral", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "orangotango": { name: "Esp\u00edrito de Luta de Orangotango", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "porco_espinho": { name: "Instinto de Porco-Espinho", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "urubu_carniceiro": { name: "Ventos Livres de Urubu Carniceiro", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "pikachu": { name: "Carga Prism\u00e1tica de Pikachu", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "brasagarto": { name: "Chama Interior de Brasagarto", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "cascatoruga": { name: "Mar\u00e9 Prism\u00e1tica de Cascatoruga", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "folhassauro": { name: "Seiva Ancestral de Folhassauro", emoji: "\ud83d\udc9a", kind: "regen", value: 0.04, description: "\u2728 regenera 4% do HP m\u00e1ximo por turno." },
  "faiscorato": { name: "Carga Prism\u00e1tica de Faiscorato", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "rochapunho": { name: "N\u00facleo de Pedra de Rochapunho", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "chamalobo": { name: "Chama Interior de Chamalobo", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "psicoluna": { name: "Mente Absoluta de Psicoluna", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "vespanoxa": { name: "Exoesqueleto Cromado de Vespanoxa", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "ventasa": { name: "Ventos Livres de Ventasa", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "dracomarino": { name: "Mar\u00e9 Prism\u00e1tica de Dracomarino", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "rinoceronte_guardiao": { name: "Pele de Rocha de Rinoceronte Guardi\u00e3o", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "elefante_ancestral": { name: "Pele de Rocha de Elefante Ancestral", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "arara_corsaria": { name: "Ventos Livres de Arara Cors\u00e1ria", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "tigre_relampago": { name: "Carga Prism\u00e1tica de Tigre Rel\u00e2mpago", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "leopardo_fantasma": { name: "V\u00e9u Espectral de Leopardo Fantasma", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "hiena_carniceira": { name: "Sombra Perfeita de Hiena Carniceira", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "coruja_branca": { name: "Ventos Livres de Coruja Branca", emoji: "\ud83d\udc9a", kind: "regen", value: 0.04, description: "\u2728 regenera 4% do HP m\u00e1ximo por turno." },
  "escorpiao_deserto": { name: "Sangue T\u00f3xico de Escorpi\u00e3o do Deserto", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "coruja_negra": { name: "V\u00e9u Espectral de Coruja Negra", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "coruja_psiquica": { name: "Mente Absoluta de Coruja Ps\u00edquica", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "alakazam": { name: "Mente Absoluta de Alakazam", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "gastly": { name: "V\u00e9u Espectral de Gastly", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "haunter": { name: "V\u00e9u Espectral de Haunter", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "abra": { name: "Mente Absoluta de Abra", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "kadabra": { name: "Mente Absoluta de Kadabra", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "charmander": { name: "Chama Interior de Charmander", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "charmeleon": { name: "Chama Interior de Charmeleon", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "charizard": { name: "Chama Interior de Charizard", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "squirtle": { name: "Mar\u00e9 Prism\u00e1tica de Squirtle", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "wartortle": { name: "Mar\u00e9 Prism\u00e1tica de Wartortle", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "blastoise": { name: "Mar\u00e9 Prism\u00e1tica de Blastoise", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "bulbasaur": { name: "Seiva Ancestral de Bulbasaur", emoji: "\ud83d\udc9a", kind: "regen", value: 0.04, description: "\u2728 regenera 4% do HP m\u00e1ximo por turno." },
  "ivysaur": { name: "Seiva Ancestral de Ivysaur", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "venusaur": { name: "Seiva Ancestral de Venusaur", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "caterpie": { name: "Exoesqueleto Cromado de Caterpie", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "metapod": { name: "Exoesqueleto Cromado de Metapod", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "butterfree": { name: "Exoesqueleto Cromado de Butterfree", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "weedle": { name: "Exoesqueleto Cromado de Weedle", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "kakuna": { name: "Exoesqueleto Cromado de Kakuna", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "beedrill": { name: "Exoesqueleto Cromado de Beedrill", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "pidgey": { name: "Instinto de Pidgey", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "pidgeotto": { name: "Instinto de Pidgeotto", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "pidgeot": { name: "Instinto de Pidgeot", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "rattata": { name: "Instinto de Rattata", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "raticate": { name: "Instinto de Raticate", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "fearow": { name: "Instinto de Fearow", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "ekans": { name: "Sangue T\u00f3xico de Ekans", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "arbok": { name: "Sangue T\u00f3xico de Arbok", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "raichu": { name: "Carga Prism\u00e1tica de Raichu", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "sandshrew": { name: "Pele de Rocha de Sandshrew", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "sandslash": { name: "Pele de Rocha de Sandslash", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "nidoran_f": { name: "Sangue T\u00f3xico de Nidoran\u2640", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "nidorina": { name: "Sangue T\u00f3xico de Nidorina", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "nidoqueen": { name: "Sangue T\u00f3xico de Nidoqueen", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "nidoran_m": { name: "Sangue T\u00f3xico de Nidoran\u2642", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "nidorino": { name: "Sangue T\u00f3xico de Nidorino", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "nidoking": { name: "Sangue T\u00f3xico de Nidoking", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "clefairy": { name: "Encanto Prism\u00e1tico de Clefairy", emoji: "\ud83d\udc9a", kind: "regen", value: 0.04, description: "\u2728 regenera 4% do HP m\u00e1ximo por turno." },
  "clefable": { name: "Encanto Prism\u00e1tico de Clefable", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "vulpix": { name: "Chama Interior de Vulpix", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "ninetales": { name: "Chama Interior de Ninetales", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "jigglypuff": { name: "Instinto de Jigglypuff", emoji: "\ud83d\udc9a", kind: "regen", value: 0.04, description: "\u2728 regenera 4% do HP m\u00e1ximo por turno." },
  "wigglytuff": { name: "Instinto de Wigglytuff", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "zubat": { name: "Sangue T\u00f3xico de Zubat", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "golbat": { name: "Sangue T\u00f3xico de Golbat", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "oddish": { name: "Seiva Ancestral de Oddish", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "gloom": { name: "Seiva Ancestral de Gloom", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "vileplume": { name: "Seiva Ancestral de Vileplume", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "paras": { name: "Exoesqueleto Cromado de Paras", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "parasect": { name: "Exoesqueleto Cromado de Parasect", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "venonat": { name: "Exoesqueleto Cromado de Venonat", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "venomoth": { name: "Exoesqueleto Cromado de Venomoth", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "diglett": { name: "Pele de Rocha de Diglett", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "dugtrio": { name: "Pele de Rocha de Dugtrio", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "meowth": { name: "Instinto de Meowth", emoji: "\u26a1", kind: "first_strike", value: 1, description: "\u2728 o primeiro golpe da batalha \u00e9 CR\u00cdTICO garantido." },
  "persian": { name: "Instinto de Persian", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "psyduck": { name: "Mar\u00e9 Prism\u00e1tica de Psyduck", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "golduck": { name: "Mar\u00e9 Prism\u00e1tica de Golduck", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "mankey": { name: "Esp\u00edrito de Luta de Mankey", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "primeape": { name: "Esp\u00edrito de Luta de Primeape", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "growlithe": { name: "Chama Interior de Growlithe", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "arcanine": { name: "Chama Interior de Arcanine", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "poliwag": { name: "Mar\u00e9 Prism\u00e1tica de Poliwag", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "poliwhirl": { name: "Mar\u00e9 Prism\u00e1tica de Poliwhirl", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "poliwrath": { name: "Mar\u00e9 Prism\u00e1tica de Poliwrath", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "machop": { name: "Esp\u00edrito de Luta de Machop", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "machoke": { name: "Esp\u00edrito de Luta de Machoke", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "machamp": { name: "Esp\u00edrito de Luta de Machamp", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "bellsprout": { name: "Seiva Ancestral de Bellsprout", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "weepinbell": { name: "Seiva Ancestral de Weepinbell", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "victreebel": { name: "Seiva Ancestral de Victreebel", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "tentacool": { name: "Mar\u00e9 Prism\u00e1tica de Tentacool", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "tentacruel": { name: "Mar\u00e9 Prism\u00e1tica de Tentacruel", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "geodude": { name: "N\u00facleo de Pedra de Geodude", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "graveler": { name: "N\u00facleo de Pedra de Graveler", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "golem": { name: "N\u00facleo de Pedra de Golem", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "ponyta": { name: "Chama Interior de Ponyta", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "rapidash": { name: "Chama Interior de Rapidash", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "slowpoke": { name: "Mar\u00e9 Prism\u00e1tica de Slowpoke", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "slowbro": { name: "Mar\u00e9 Prism\u00e1tica de Slowbro", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "magnemite": { name: "Carga Prism\u00e1tica de Magnemite", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "magneton": { name: "Carga Prism\u00e1tica de Magneton", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "farfetchd": { name: "Instinto de Farfetch'd", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "doduo": { name: "Instinto de Doduo", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "dodrio": { name: "Instinto de Dodrio", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "seel": { name: "Mar\u00e9 Prism\u00e1tica de Seel", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "dewgong": { name: "Mar\u00e9 Prism\u00e1tica de Dewgong", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "grimer": { name: "Sangue T\u00f3xico de Grimer", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "muk": { name: "Sangue T\u00f3xico de Muk", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "shellder": { name: "Mar\u00e9 Prism\u00e1tica de Shellder", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "cloyster": { name: "Mar\u00e9 Prism\u00e1tica de Cloyster", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "onix": { name: "N\u00facleo de Pedra de Onix", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "drowzee": { name: "Mente Absoluta de Drowzee", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "hypno": { name: "Mente Absoluta de Hypno", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "krabby": { name: "Mar\u00e9 Prism\u00e1tica de Krabby", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "kingler": { name: "Mar\u00e9 Prism\u00e1tica de Kingler", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "voltorb": { name: "Carga Prism\u00e1tica de Voltorb", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "electrode": { name: "Carga Prism\u00e1tica de Electrode", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "exeggcute": { name: "Seiva Ancestral de Exeggcute", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "exeggutor": { name: "Seiva Ancestral de Exeggutor", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "cubone": { name: "Pele de Rocha de Cubone", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "marowak": { name: "Pele de Rocha de Marowak", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "hitmonlee": { name: "Esp\u00edrito de Luta de Hitmonlee", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "hitmonchan": { name: "Esp\u00edrito de Luta de Hitmonchan", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "lickitung": { name: "Instinto de Lickitung", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "koffing": { name: "Sangue T\u00f3xico de Koffing", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "weezing": { name: "Sangue T\u00f3xico de Weezing", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "rhyhorn": { name: "Pele de Rocha de Rhyhorn", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "rhydon": { name: "Pele de Rocha de Rhydon", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "chansey": { name: "Instinto de Chansey", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "tangela": { name: "Seiva Ancestral de Tangela", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "kangaskhan": { name: "Instinto de Kangaskhan", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "horsea": { name: "Mar\u00e9 Prism\u00e1tica de Horsea", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "seadra": { name: "Mar\u00e9 Prism\u00e1tica de Seadra", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "goldeen": { name: "Mar\u00e9 Prism\u00e1tica de Goldeen", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "seaking": { name: "Mar\u00e9 Prism\u00e1tica de Seaking", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "staryu": { name: "Mar\u00e9 Prism\u00e1tica de Staryu", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "starmie": { name: "Mar\u00e9 Prism\u00e1tica de Starmie", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "mrmime": { name: "Mente Absoluta de Mr. Mime", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "scyther": { name: "Exoesqueleto Cromado de Scyther", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "jynx": { name: "Cora\u00e7\u00e3o de Gelo de Jynx", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "electabuzz": { name: "Carga Prism\u00e1tica de Electabuzz", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "magmar": { name: "Chama Interior de Magmar", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "pinsir": { name: "Exoesqueleto Cromado de Pinsir", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "tauros": { name: "Instinto de Tauros", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "magikarp": { name: "Mar\u00e9 Prism\u00e1tica de Magikarp", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "gyarados": { name: "Mar\u00e9 Prism\u00e1tica de Gyarados", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "lapras": { name: "Mar\u00e9 Prism\u00e1tica de Lapras", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "ditto": { name: "Instinto de Ditto", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "eevee": { name: "Instinto de Eevee", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "vaporeon": { name: "Mar\u00e9 Prism\u00e1tica de Vaporeon", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "jolteon": { name: "Carga Prism\u00e1tica de Jolteon", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "flareon": { name: "Chama Interior de Flareon", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "porygon": { name: "Instinto de Porygon", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "omanyte": { name: "N\u00facleo de Pedra de Omanyte", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "kabuto": { name: "N\u00facleo de Pedra de Kabuto", emoji: "\ud83c\udf35", kind: "thorns", value: 0.15, description: "\u2728 reflete 15% do dano recebido no atacante." },
  "kabutops": { name: "N\u00facleo de Pedra de Kabutops", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "aerodactyl": { name: "N\u00facleo de Pedra de Aerodactyl", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "snorlax": { name: "Instinto de Snorlax", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "articuno": { name: "Cora\u00e7\u00e3o de Gelo de Articuno", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "zapdos": { name: "Carga Prism\u00e1tica de Zapdos", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "moltres": { name: "Chama Interior de Moltres", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "dratini": { name: "Heran\u00e7a Drac\u00f4nica de Dratini", emoji: "\ud83d\udca2", kind: "vengeance", value: 0.5, description: "\u2728 ganha at\u00e9 +50% de ATK conforme perde HP." },
  "dragonair": { name: "Heran\u00e7a Drac\u00f4nica de Dragonair", emoji: "\ud83c\udfaf", kind: "cc_master", value: 0.25, description: "\u2728 +25% de chance em todos os efeitos secund\u00e1rios dos golpes." },
  "dragonite": { name: "Heran\u00e7a Drac\u00f4nica de Dragonite", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "omastar": { name: "N\u00facleo de Pedra de Omastar", emoji: "\ud83e\ude78", kind: "leech", value: 0.25, description: "\u2728 cura 25% do dano causado." },
  "mewtwo": { name: "Mente Absoluta de Mewtwo", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
  "mew": { name: "Mente Absoluta de Mew", emoji: "\u2728", kind: "type_boost", value: 0.25, description: "\u2728 +25% de dano com golpes do seu tipo principal." },
};
