/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreviewChestRouteImport } from './routes/preview-chest'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as ExpeditionsRouteImport } from './routes/expeditions'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonsterIdRouteImport } from './routes/monster.$id'
import { Route as FriendsFriendIdRouteImport } from './routes/friends.$friendId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewChestRoute = PreviewChestRouteImport.update({
  id: '/preview-chest',
  path: '/preview-chest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionsRoute = ExpeditionsRouteImport.update({
  id: '/expeditions',
  path: '/expeditions',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonsterIdRoute = MonsterIdRouteImport.update({
  id: '/monster/$id',
  path: '/monster/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsFriendIdRoute = FriendsFriendIdRouteImport.update({
  id: '/$friendId',
  path: '/$friendId',
  getParentRoute: () => FriendsRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena': typeof ArenaRoute
  '/collection': typeof CollectionRoute
  '/expeditions': typeof ExpeditionsRoute
  '/forge': typeof ForgeRoute
  '/friends': typeof FriendsRouteWithChildren
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/preview-chest': typeof PreviewChestRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/redeem': typeof RedeemRoute
  '/refunds': typeof RefundsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/tournament': typeof TournamentRoute
  '/trade': typeof TradeRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/monster/$id': typeof MonsterIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena': typeof ArenaRoute
  '/collection': typeof CollectionRoute
  '/expeditions': typeof ExpeditionsRoute
  '/forge': typeof ForgeRoute
  '/friends': typeof FriendsRouteWithChildren
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/preview-chest': typeof PreviewChestRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/redeem': typeof RedeemRoute
  '/refunds': typeof RefundsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/tournament': typeof TournamentRoute
  '/trade': typeof TradeRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/monster/$id': typeof MonsterIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena': typeof ArenaRoute
  '/collection': typeof CollectionRoute
  '/expeditions': typeof ExpeditionsRoute
  '/forge': typeof ForgeRoute
  '/friends': typeof FriendsRouteWithChildren
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/preview-chest': typeof PreviewChestRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/redeem': typeof RedeemRoute
  '/refunds': typeof RefundsRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/tournament': typeof TournamentRoute
  '/trade': typeof TradeRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/monster/$id': typeof MonsterIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arena'
    | '/collection'
    | '/expeditions'
    | '/forge'
    | '/friends'
    | '/history'
    | '/login'
    | '/preview-chest'
    | '/privacy'
    | '/profile'
    | '/ranking'
    | '/redeem'
    | '/refunds'
    | '/shop'
    | '/terms'
    | '/tournament'
    | '/trade'
    | '/friends/$friendId'
    | '/monster/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/arena'
    | '/collection'
    | '/expeditions'
    | '/forge'
    | '/friends'
    | '/history'
    | '/login'
    | '/preview-chest'
    | '/privacy'
    | '/profile'
    | '/ranking'
    | '/redeem'
    | '/refunds'
    | '/shop'
    | '/terms'
    | '/tournament'
    | '/trade'
    | '/friends/$friendId'
    | '/monster/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arena'
    | '/collection'
    | '/expeditions'
    | '/forge'
    | '/friends'
    | '/history'
    | '/login'
    | '/preview-chest'
    | '/privacy'
    | '/profile'
    | '/ranking'
    | '/redeem'
    | '/refunds'
    | '/shop'
    | '/terms'
    | '/tournament'
    | '/trade'
    | '/friends/$friendId'
    | '/monster/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArenaRoute: typeof ArenaRoute
  CollectionRoute: typeof CollectionRoute
  ExpeditionsRoute: typeof ExpeditionsRoute
  ForgeRoute: typeof ForgeRoute
  FriendsRoute: typeof FriendsRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  PreviewChestRoute: typeof PreviewChestRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  RedeemRoute: typeof RedeemRoute
  RefundsRoute: typeof RefundsRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  TournamentRoute: typeof TournamentRoute
  TradeRoute: typeof TradeRoute
  MonsterIdRoute: typeof MonsterIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-chest': {
      id: '/preview-chest'
      path: '/preview-chest'
      fullPath: '/preview-chest'
      preLoaderRoute: typeof PreviewChestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditions': {
      id: '/expeditions'
      path: '/expeditions'
      fullPath: '/expeditions'
      preLoaderRoute: typeof ExpeditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monster/$id': {
      id: '/monster/$id'
      path: '/monster/$id'
      fullPath: '/monster/$id'
      preLoaderRoute: typeof MonsterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/$friendId': {
      id: '/friends/$friendId'
      path: '/$friendId'
      fullPath: '/friends/$friendId'
      preLoaderRoute: typeof FriendsFriendIdRouteImport
      parentRoute: typeof FriendsRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FriendsRouteChildren {
  FriendsFriendIdRoute: typeof FriendsFriendIdRoute
}

const FriendsRouteChildren: FriendsRouteChildren = {
  FriendsFriendIdRoute: FriendsFriendIdRoute,
}

const FriendsRouteWithChildren =
  FriendsRoute._addFileChildren(FriendsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArenaRoute: ArenaRoute,
  CollectionRoute: CollectionRoute,
  ExpeditionsRoute: ExpeditionsRoute,
  ForgeRoute: ForgeRoute,
  FriendsRoute: FriendsRouteWithChildren,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  PreviewChestRoute: PreviewChestRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  RedeemRoute: RedeemRoute,
  RefundsRoute: RefundsRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  TournamentRoute: TournamentRoute,
  TradeRoute: TradeRoute,
  MonsterIdRoute: MonsterIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
