/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgeRouteImport } from './routes/forge'
import { Route as ExpeditionsRouteImport } from './routes/expeditions'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MonsterIdRouteImport } from './routes/monster.$id'

const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgeRoute = ForgeRouteImport.update({
  id: '/forge',
  path: '/forge',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditionsRoute = ExpeditionsRouteImport.update({
  id: '/expeditions',
  path: '/expeditions',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonsterIdRoute = MonsterIdRouteImport.update({
  id: '/monster/$id',
  path: '/monster/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/collection': typeof CollectionRoute
  '/expeditions': typeof ExpeditionsRoute
  '/forge': typeof ForgeRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/trade': typeof TradeRoute
  '/monster/$id': typeof MonsterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/collection': typeof CollectionRoute
  '/expeditions': typeof ExpeditionsRoute
  '/forge': typeof ForgeRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/trade': typeof TradeRoute
  '/monster/$id': typeof MonsterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/collection': typeof CollectionRoute
  '/expeditions': typeof ExpeditionsRoute
  '/forge': typeof ForgeRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/trade': typeof TradeRoute
  '/monster/$id': typeof MonsterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/collection'
    | '/expeditions'
    | '/forge'
    | '/login'
    | '/shop'
    | '/trade'
    | '/monster/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/collection'
    | '/expeditions'
    | '/forge'
    | '/login'
    | '/shop'
    | '/trade'
    | '/monster/$id'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/collection'
    | '/expeditions'
    | '/forge'
    | '/login'
    | '/shop'
    | '/trade'
    | '/monster/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRoute: typeof ArenaRoute
  CollectionRoute: typeof CollectionRoute
  ExpeditionsRoute: typeof ExpeditionsRoute
  ForgeRoute: typeof ForgeRoute
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRoute
  TradeRoute: typeof TradeRoute
  MonsterIdRoute: typeof MonsterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forge': {
      id: '/forge'
      path: '/forge'
      fullPath: '/forge'
      preLoaderRoute: typeof ForgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expeditions': {
      id: '/expeditions'
      path: '/expeditions'
      fullPath: '/expeditions'
      preLoaderRoute: typeof ExpeditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monster/$id': {
      id: '/monster/$id'
      path: '/monster/$id'
      fullPath: '/monster/$id'
      preLoaderRoute: typeof MonsterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRoute: ArenaRoute,
  CollectionRoute: CollectionRoute,
  ExpeditionsRoute: ExpeditionsRoute,
  ForgeRoute: ForgeRoute,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRoute,
  TradeRoute: TradeRoute,
  MonsterIdRoute: MonsterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
